/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./node_modules/flowbite-react/lib/**/*.{js,ts}",
    "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js",
    "./src/**/*.{ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        gray: {
          50: "#f9fafb",
          100: "#f3f4f6",
          200: "#e5e7eb",
          300: "#e5e7eb",
        },
      },
      borderRadius: {
        md: "0.375rem",
        lg: "0.8rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
    colors: {
      primary: {
        50: "#FFFDF5",
        100: "#FFFAE5",
        200: "#FFF4CC",
        300: "#FFEFB3",
        400: "#FFE685",
        500: "#FFDE5C",
        600: "#FFD42E",
        700: "#FFCB00",
        800: "#CCA200",
        900: "#997A00",
      },
    },
    fontSize: {
      xs: "0.8rem",
      sm: "0.9rem",
      base: "0.95rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.4rem",
      "3xl": "1.5rem",
      "4xl": "2.441rem",
      "5xl": "2.5rem",
      "6xl": "3.052rem",
      "7xl": "4rem",
    },
    fontFamily: {
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
  },
  plugins: [require("flowbite/plugin")],
};
